// <auto-generated />
using System;
using DACN.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DACN.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250718131748_AddMaKhachHangToChiTietThanhToanDV")]
    partial class AddMaKhachHangToChiTietThanhToanDV
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("DACN.Models.BaoCao", b =>
                {
                    b.Property<int>("MaBaoCao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("LoaiBaoCao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("TEXT");

                    b.Property<string>("NguoiTao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhamViThoiGian")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("chi_tiet")
                        .HasColumnType("TEXT");

                    b.Property<string>("trang_thai")
                        .HasColumnType("TEXT");

                    b.HasKey("MaBaoCao");

                    b.ToTable("BaoCao");
                });

            modelBuilder.Entity("DACN.Models.ChamCong", b =>
                {
                    b.Property<int>("MaChamCong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AnhNhanDienKhuonMat")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GhiChu")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MaNhanVien")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("NgayGioKetCa")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("NgayGioVaoCa")
                        .HasColumnType("TEXT");

                    b.HasKey("MaChamCong");

                    b.ToTable("ChamCong");
                });

            modelBuilder.Entity("DACN.Models.ChiTietThanhToan", b =>
                {
                    b.Property<int>("MaChiTiet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("DonGia")
                        .HasColumnType("TEXT");

                    b.Property<string>("HinhThucThanhToan")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MaDichVu")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaThanhToan")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SoLuong")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("ThanhTien")
                        .HasColumnType("TEXT");

                    b.HasKey("MaChiTiet");

                    b.ToTable("ChiTietThanhToan");
                });

            modelBuilder.Entity("DACN.Models.ChiTietThanhToanDV", b =>
                {
                    b.Property<int>("MaChiTiet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("GhiChu")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HinhThucThanhToan")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MaDichVu")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MaKhachHang")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("NgayThanhToan")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TongTien")
                        .HasColumnType("TEXT");

                    b.HasKey("MaChiTiet");

                    b.HasIndex("MaKhachHang");

                    b.ToTable("ChiTietThanhToanDV");
                });

            modelBuilder.Entity("DACN.Models.DatDichVu", b =>
                {
                    b.Property<int>("MaDatDichVu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("GhiChu")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MaDichVu")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaKhachHang")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("NgaySuDung")
                        .HasColumnType("TEXT");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("MaDatDichVu");

                    b.ToTable("DatDichVu");
                });

            modelBuilder.Entity("DACN.Models.DatPhong", b =>
                {
                    b.Property<int>("MaDatPhong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("GhiChu")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HinhThucThanhToan")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MaKhachHang")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaPhong")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("NgayDat")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("NgayNhan")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("NgayNhanPhong")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("NgayTra")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("NgayTraPhong")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TongTien")
                        .HasColumnType("TEXT");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("MaDatPhong");

                    b.HasIndex("MaKhachHang");

                    b.HasIndex("MaPhong");

                    b.ToTable("DatPhong");
                });

            modelBuilder.Entity("DACN.Models.DichVu", b =>
                {
                    b.Property<int>("MaDichVu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("GiaDichVu")
                        .HasColumnType("TEXT");

                    b.Property<string>("HinhAnh")
                        .HasColumnType("TEXT");

                    b.Property<string>("MoTa")
                        .HasColumnType("TEXT");

                    b.Property<string>("MucLuc")
                        .HasColumnType("TEXT");

                    b.Property<string>("TenDichVu")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("MaDichVu");

                    b.ToTable("DichVu");
                });

            modelBuilder.Entity("DACN.Models.GioHang", b =>
                {
                    b.Property<int>("MaGioHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("DonGia")
                        .HasColumnType("TEXT");

                    b.Property<string>("GhiChu")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MaDichVu")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaKhachHang")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("NgayThem")
                        .HasColumnType("TEXT");

                    b.Property<int>("SoLuong")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("ThanhTien")
                        .HasColumnType("TEXT");

                    b.HasKey("MaGioHang");

                    b.HasIndex("MaDichVu");

                    b.ToTable("GioHang");
                });

            modelBuilder.Entity("DACN.Models.KhachHang", b =>
                {
                    b.Property<int>("MaKhachHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("MaKhachHang");

                    b.ToTable("KhachHang");
                });

            modelBuilder.Entity("DACN.Models.NhanVien", b =>
                {
                    b.Property<int>("MaNhanVien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CaLamViec")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GioiTinh")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HinhAnhKhuonMat")
                        .HasColumnType("TEXT");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TaiKhoanDangNhap")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ViTri")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("MaNhanVien");

                    b.ToTable("NhanVien");
                });

            modelBuilder.Entity("DACN.Models.PhieuHuHai", b =>
                {
                    b.Property<int>("MaPhieu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("ChiPhiBoiThuong")
                        .HasColumnType("TEXT");

                    b.Property<int>("MaPhong")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MucDoHuHai")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NguyenNhan")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("PhongMaPhong")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TenThietBi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ThoiGianGhiNhan")
                        .HasColumnType("TEXT");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("MaPhieu");

                    b.HasIndex("PhongMaPhong");

                    b.ToTable("PhieuHuHai");
                });

            modelBuilder.Entity("DACN.Models.Phong", b =>
                {
                    b.Property<int>("MaPhong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("GiaPhong")
                        .HasColumnType("TEXT");

                    b.Property<string>("HinhAnh")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoaiPhong")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MoTa")
                        .HasColumnType("TEXT");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("MaPhong");

                    b.ToTable("Phong");
                });

            modelBuilder.Entity("DACN.Models.SliderModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("HienThi")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HinhAnh")
                        .HasColumnType("TEXT");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Sliders");
                });

            modelBuilder.Entity("DACN.Models.TaiKhoan", b =>
                {
                    b.Property<string>("TenDangNhap")
                        .HasColumnType("TEXT");

                    b.Property<bool>("BaoMat2FA")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("QuyenTruyCap")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("TenDangNhap");

                    b.ToTable("TaiKhoan");
                });

            modelBuilder.Entity("DACN.Models.ThanhToan", b =>
                {
                    b.Property<int>("MaThanhToan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("HinhThucThanhToan")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MaDatPhong")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaKhachHang")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("NgayThanhToan")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SoTien")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TongTien")
                        .HasColumnType("TEXT");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("MaThanhToan");

                    b.ToTable("ThanhToan");
                });

            modelBuilder.Entity("DACN.Models.ChiTietThanhToanDV", b =>
                {
                    b.HasOne("DACN.Models.KhachHang", "KhachHang")
                        .WithMany()
                        .HasForeignKey("MaKhachHang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhachHang");
                });

            modelBuilder.Entity("DACN.Models.DatPhong", b =>
                {
                    b.HasOne("DACN.Models.KhachHang", "KhachHang")
                        .WithMany()
                        .HasForeignKey("MaKhachHang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DACN.Models.Phong", "Phong")
                        .WithMany()
                        .HasForeignKey("MaPhong")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhachHang");

                    b.Navigation("Phong");
                });

            modelBuilder.Entity("DACN.Models.GioHang", b =>
                {
                    b.HasOne("DACN.Models.DichVu", "DichVu")
                        .WithMany()
                        .HasForeignKey("MaDichVu")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DichVu");
                });

            modelBuilder.Entity("DACN.Models.PhieuHuHai", b =>
                {
                    b.HasOne("DACN.Models.Phong", "Phong")
                        .WithMany()
                        .HasForeignKey("PhongMaPhong");

                    b.Navigation("Phong");
                });
#pragma warning restore 612, 618
        }
    }
}
